version: "3.8"
services:
  node:
    image: node:lts
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "node.js"
    volumes:
      - html:/home/node
    working_dir: /home/node/next
    user: node
    command: /bin/sh -c "while sleep 1000; do :; done"

#    expose:
#      - 3000:3000
volumes:
  html:
