import Head from 'next/head'
import * as fs from 'fs'


type props = {
    files :string[],
}

export default function Component({files, } :props)
{
    return <>
        <Head>
            <title>Reactions</title>
            <meta name="description" content="Generated by create next app" />
        </Head>
        <main>
            <article>
                <section>
                    <h2>Examples</h2>
                    <ul>
                    {
                        files.map((file) => {
                        return <li key={`${file}`}>
                            <a href={`/examples/${file}`}>{file}</a>
                        </li>
                        })
                    }
                    </ul>
                </section>
            </article>
        </main>
    </>
}


export async function getStaticProps()
{
    const f = fs.readdirSync('./pages/examples')
    const files = f.map((i) => i.replace('.tsx', ''))
    return {
        props: {
            files
        }
    }

}